### ISSUE TITLE
Templates should include Travis CI configuration

### ISSUE THREAD

**Issue by imaustink** [donejs/generator-donejs#264]
Using Testee to launch FireFox on Travis requires special configuration to prevent errors. A default configuration should be added to the `plugin`, and probably the `app` templates.

This is the required configureation, note the `dbus` installation:
```yml
language: node_js
node_js:
  - "6"
addons:
  firefox: "latest-esr"
  apt:
    packages:
      - dbus-x11
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```

For more information about this issue, see https://github.com/bitovi/testee/issues/157.

cc: @phillipskevin, @matthewp
